### ISSUE TITLE
Review for Portolio Project

### ISSUE THREAD

**Issue by chelmerrox** [Ghilain/ghilain-portfolio#5]
Great job so far! 😃

- You've used grid & flex-box well. 
- Your project is also following the requirements & the template you've chosen.
- maybe you should use more semantic HTML for e.g in your header, you could use a `<header>` tag instead of a `<div>`

**Comment by Ghilain** [comment]
Thank you

**Comment by Christabelle143** [comment]
Great job Ghislain 👍 .
